
services:
  flask:
    build: ./Flask
    container_name: flask-container
    ports:
      - '5000:5000'
    depends_on:
      - api
    networks:
      - my-network
#--------------------------------------
  php:
    build: ./Php
    container_name: php-container
    ports:
      - '3002:80'
    depends_on:
      - api
    networks:
      - my-network
#--------------------------------------
  api:
    build: ./backend-api
    container_name: backend-api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - my-network
#---------------------------------------
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
#-----------------------------------------
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: always
    networks:
      - my-network

  loadgenservice:
    build: ./LoadGenService
    ports:
      - "5001:5001"
    networks:
      - my-network

  loggingservice:
    build: ./LoggingService
    ports:
      - "5002:5002"
    networks:
      - my-network

volumes:
  mongo-data:
networks:
  my-network:
